backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
site_url: https://ghasemzadeh.com/admin
display_url: https://ghasemzadeh.com
collections:
  - label: "News"
    name: "pages"
    files:
      - label: "Add/Edit News"
        name: "news"
        file: "content/news.md"
        format: 'frontmatter'
        fields:
          - {label: 'Body', name: body, widget: markdown}
  - label: "Publications"
    name: "publications"
    folder: "content/publication/"
    path: '{{slug}}/index'
    media_folder: ''
    create: true
    fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publication", name: "publication", widget: "string"}
          - label: "Publication Type"
            name: "publication_types"
            required: false
            widget: "list"
            default: ["0"]
            hint: "Use 0 for Uncategorized, 1 for Conference Paper, 2 for Journal Article"
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "PDF URL", name: "url_pdf", widget: "string", required: false}
          - {label: "Code URL", name: "url_code", widget: "string", required: false}
          - {label: 'Abstract', name: abstract, widget: markdown, required: false}
