backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
site_url: https://ghasemzadeh.com
collections:
  - name: 'news'
    label: 'news'
    description: 'Add/Edit the news section'
    file: 'content/news.md'
    format: 'frontmatter'
    create: false
    editor:
      preview: true
    fields:
      - { label: 'Body', name: 'body', widget: 'markdown' }
