backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
site_url: https://ghasemzadeh.com/admin
display_url: https://ghasemzadeh.com
collections:
  - label: "News"
    name: "pages"
    files:
      - label: "Add/Edit News"
        name: "news"
        file: "content/news.md"
        format: 'frontmatter'
        fields:
          - {label: 'Body', name: body, widget: markdown}
  - label: "Publications"
    name: "publications"
    folder: "content/publication/"
    path: '{{slug}}/index'
    media_folder: ''
    create: true
    fields:
          - {label: "Title", name: "title", widget: "string", hint: "Title of the paper"}
          - {label: "Publication", name: "publication", widget: "string", hint: "publication venue. E.g., IEEE sensors Journal or ArXiv"}
          - label: "Publication Type"
            name: "publication_types"
            required: false
            widget: "list"
            default: ["0"]
            hint: "Use 0 for Uncategorized, 1 for Conference Paper, 2 for Journal Article, and 3 for Pre-Print"
          - label: "Authors"
            name: "authors"
            widget: "list"
            required: true
            allow_add: true
            hint: "Enter author list COMMA SEPARATED (e.g., author one, author two)"
          - label: "Featured Image"
            name: "image2"
            widget: "image"
            required: false
            hint: "If you upload an image, the name of the file HAS TO BE featured.png or featured.jpg"
            pattern: ['^$|featured\.(png|jpg)', "must be either empty or featured.png or featured.jpg"]
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "PDF URL", name: "url_pdf", widget: "string", required: false}
          - {label: "Code URL", name: "url_code", widget: "string", required: false}
          - {label: 'Abstract', name: abstract, widget: markdown, required: false}
  - label: "Projects"
    name: "projects"
    folder: "content/project/"
    path: '{{slug}}/index'
    media_folder: ''
    create: true
    format: 'frontmatter'
    fields:
          - {label: "Title", name: "title", widget: "string", hint: "Title of the project"}
          - {label: "Summary", name: "summary", widget: "text", hint: "Short summary of the project (less than 200 characters)"}
          - label: "Featured Image"
            name: "image2"
            widget: "image"
            required: false
            hint: "If you upload an image, the name of the file HAS TO BE featured.png or featured.jpg"
            pattern: ['^$|featured\.(png|jpg)', "must be either empty or featured.png or featured.jpg"]
          - {label: "Date", name: "date", widget: "datetime"}
          - {label: 'Body', name: body, widget: markdown, hint: "Long description of the project"}
  - name: authors
    label: People
    folder: 'content/authors'
    path: '{{slug}}/_index'
    create: true  # Allow users to create new documents in this collection
    fields:  # The fields each document in this collection have
      - {label: "Display name (such as your full name)", name: "name", widget: "string"}
      - {label: "Position or tagline (such as Professor of AI)", name: "role", widget: "string", required: false}
      - label: "Avatar (upload an image named `avatar.jpg/png`)"
        name: "avatar_filename"
        widget: "image"
        default: "avatar"
        required: false
        media_library:
          config:
            multiple: false
      - {label: "Short biography (shown in author boxes)", name: "bio", widget: "string", required: false}
      - {label: "Full biography (shown in About widget)", name: "body", widget: "markdown", required: false}
      - label: Social links
        name: social
        required: false
        widget: list
        fields:
          - {label: Link, name: link, widget: string}
          - label: Icon pack
            name: icon_pack
            widget: select
            multiple: false
            options:
              - {label: "None", value: ""}
              - {label: "Solid", value: "fas"}
              - {label: "Regular", value: "far"}
              - {label: "Brand", value: "fab"}
              - {label: "Academic", value: "ai"}
          - {label: Icon (see https://sourcethemes.com/academic/docs/page-builder/#icons), name: icon, widget: string}
      - label: "Organizations you belong to or are affiliated with (shown in About widget)"
        name: "organizations"
        required: false
        widget: list
        fields:
          - {label: Organization, name: name, widget: string, required: true}
          - {label: Link, name: url, widget: string, required: false}
      - {label: "Email (to use a Gravatar.com avatar)", name: "email", widget: "string", required: false}
      - label: "Super user (is this the primary site user?)"
        name: "superuser"
        widget: "boolean"
        default: false
      - label: "User groups (only for organization websites)"
        name: "user_groups"
        required: false
        widget: "list"
